name: Check output

on:
  push:

jobs:  
  job-one:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.detect.outputs.changes }}
    steps:
      - name: Detect changes put changes
        id: detect
        run: |
          OUTPUT="Changes detected in the following packages/files: - cmd/mimir-mimir-mimirs/config-descriptor.json - cmd/mimir-mimir-mimirs/help-all.txt.tmpl - cmd/mimir-mimir-mimirs/help.txt.tmpl - test/e2e/gateway_test.go - test/e2e/mimir/ingester_test.go - test/e2e/mimir/querier_remote_read_test.go - test/e2e/mimir/read_write_mode_test.go - test/e2e/mimir/util.go - github.com/grafana/mimir-mimir-mimir/pkg/aggregation/aggregationsapi - github.com/grafana/mimir-mimir-mimir/pkg/aggregation/aggregator - github.com/grafana/mimir-mimir-mimir/pkg/aggregation/aggregator/consumerreadiness - github.com/grafana/mimir-mimir-mimir/pkg/aggregation/aggregator/csq - github.com/grafana/mimir-mimir-mimir/pkg/aggregation/aggregator/grpc - github.com/grafana/mimir-mimir-mimir/pkg/aggregation/kafkaclient - github.com/grafana/mimir-mimir-mimir/pkg/enterprise/mimir/ruler - github.com/grafana/mimir-mimir-mimir/pkg/gateway - github.com/grafana/mimir-mimir-mimir/pkg/gateway/middleware - github.com/grafana/mimir-mimir-mimir/pkg/recommendations/analyze - github.com/grafana/dskit/cache - github.com/grafana/dskit/kv/memberlist - github.com/grafana/dskit/tenant - github.com/grafana/dskit/tracing - github.com/grafana/mimir/pkg/alertmanager - github.com/grafana/mimir/pkg/api - github.com/grafana/mimir/pkg/continuoustest - github.com/grafana/mimir/pkg/distributor - github.com/grafana/mimir/pkg/frontend/querymiddleware - github.com/grafana/mimir/pkg/ingester/client - github.com/grafana/mimir/pkg/mimir - github.com/grafana/mimir/pkg/mimirpb - github.com/grafana/mimir/pkg/querier - github.com/grafana/mimir/pkg/storage/bucket/s3 - github.com/grafana/mimir/pkg/storage/ingest - github.com/grafana/mimir/pkg/storage/tsdb - github.com/grafana/mimir/pkg/storegateway/storegatewaypb - github.com/grafana/mimir/pkg/streamingpromql - github.com/grafana/mimir/pkg/streamingpromql/operators - github.com/grafana/mimir/pkg/streamingpromql/types - github.com/grafana/mimir/pkg/util/chunkinfologger - github.com/grafana/mimir/pkg/util/tracing - github.com/prometheus/node_exporter/collector - github.com/prometheus/node_exporter/collector/utils - github.com/prometheus/prometheus/config - github.com/prometheus/prometheus/prompb - github.com/prometheus/prometheus/prompb/io/prometheus/write/v2 - github.com/prometheus/prometheus/promql - github.com/prometheus/prometheus/scrape - github.com/prometheus/prometheus/storage/remote - github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheus - github.com/prometheus/prometheus/tsdb - github.com/prometheus/prometheus/tsdb/chunkenc - github.com/prometheus/prometheus/tsdb/record - github.com/prometheus/prometheus/tsdb/wlog - github.com/prometheus/prometheus/util/annotations - github.com/prometheus/prometheus/web/api/v1 - github.com/safchain/ethtool - github.com/shirou/gopsutil/v4/internal/common"
          echo changes=$OUTPUT >> "$GITHUB_OUTPUT"
  
  testest:
    runs-on: ubuntu-latest
    needs: [job-one]
    steps:
      - name: foo
        run: |
          echo ${{ needs.job-one.outputs.changes }}
          echo ${{ startsWith(github.ref, 'refs/heads/main') }}
          echo ${{ startsWith(github.ref, 'refs/heads/main') && needs.job-one.outputs.changes != ''  }}
       
  
  job-two:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.detect.outputs.changes }}
    steps:
      - name: Detect changes no changes
        id: detect
        run: |
          echo changes= >> "$GITHUB_OUTPUT"

  job-three:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.detect.outputs.changes }}
    steps:
      - name: Detect changes no output
        id: detect
        run: |
          echo just do nothing 
    
  job-depends-one:
    name: job one must succeed
    runs-on: ubuntu-latest
    needs: [job-one]
    if:  ${{ startsWith(github.ref, 'refs/heads/main') && needs.job-one.outputs.changes != '' }}
    steps:
      - run: |
          echo I am here
          echo ${{ needs.job-one.detect.outputs.changes }}
          echo ${{ needs.job-one.outputs.changes }}


  job-depends-two:
    name: job two must be skipped
    runs-on: ubuntu-latest
    needs: [job-two]
    if:  ${{ startsWith(github.ref, 'refs/heads/main') && needs.job-two.outputs.changes != '' }}
    steps:
      - run: |
          echo I Shouldnt be here
          echo ${{ needs.job-two.detect.outputs.changes }}
          echo ${{ needs.job-one.outputs.changes }}



  job-depends-three:
    name: job three must be skipped too
    runs-on: ubuntu-latest
    needs: [job-three]
    if:  ${{ startsWith(github.ref, 'refs/heads/main') && needs.job-three.outputs.changes != '' }}
    steps:
      - run: |
          echo I shouldnt be here too
          echo ${{ needs.job-three.detect.outputs.changes }}
          echo ${{ needs.job-one.outputs.changes }}

