name: Must run after success 

on:
    workflow_run: 
        workflows: 
            - Success
        types: 
            - completed 
        branches: 
            - test-this
            - test-that
            - main
            - v*



jobs:
    run-depend:
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{ github.event.workflow_run.head_branch }} 
            - run: |
                echo worflow: '${{ github.workflow }}'
                echo github: '${{ toJson(github) }}'
                echo event: '${{ toJson(github.event) }}'
                echo workflow workflow_run: '${{ toJson(github.event.workflow_run) }}'
                echo workflow head_branch: ${{ github.event.workflow_run.head_branch }}
                echo default_branch: ${{ github.event.repository.default_branch }}
                echo ref_name: ${{ github.ref_name }}
                echo head_ref: ${{ github.head_ref }}
                echo ref: ${{ github.ref }}
                echo workflow_run conclusion: ${{ github.event.workflow_run.conclusion }} 
            - run: echo "Dependent on success, should run"
              if: github.event.workflow_run.conclusion == 'success'
            - run: echo "Dependent on success"
            - uses: actions/checkout@v4
              with:
                ref: v1
                fetch-depth: 0