name: 'End to end test'
description: 'Running end to end test'
inputs:
  input_message:
    description: golang version
    required: false
    default: hello world
runs:
  using: 'composite'
  steps:
    - run: echo $GITHUB_SHA
      shell: bash
      env: 
        GITHUB_SHA: ${{ github.event.pull_request.base.sha }}
    - run: echo ${{ inputs.input_message }}
      shell: bash
    - run: echo $INPUT_ENV
      shell: bash
    - run: echo $HAHA
      env: 
        HAHA: "default ahaha"
      shell: bash
