name: Check output

on:
  push:

jobs:
  job-one:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.detect.outputs.changes }}
    steps:
      - name: Detect changes put changes
        id: detect
        run: |
          echo changes=yes >> "$GITHUB_OUTPUT"
          
  
  job-two:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.detect.outputs.changes }}
    steps:
      - name: Detect changes no changes
        id: detect
        run: |
          echo changes= >> "$GITHUB_OUTPUT"

  job-three:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.detect.outputs.changes }}
    steps:
      - name: Detect changes no output
        id: detect
        run: |
          echo just do nothing 
    
  job-depends-one:
    name: job one must succeed
    runs-on: ubuntu-latest
    needs: [job-one]
    if:  startsWith(github.ref, 'refs/head/main') && needs.job-one.outputs.changes != '' 
    steps:
      - run: |
          echo I am here
          echo ${{ needs.job-one.detect.outputs.changes }}
          echo ${{ needs.job-one.outputs.changes }}


  job-depends-two:
    name: job two must be skipped
    runs-on: ubuntu-latest
    needs: [job-two]
    if:  startsWith(github.ref, 'refs/head/main') && needs.job-two.outputs.changes != '' 
    steps:
      - run: |
          echo I Shouldnt be here
          echo ${{ needs.job-two.detect.outputs.changes }}
          echo ${{ needs.job-one.outputs.changes }}



  job-depends-three:
    name: job three must be skipped too
    runs-on: ubuntu-latest
    needs: [job-three]
    if:  startsWith(github.ref, 'refs/head/main') && needs.job-three.outputs.changes != '' 
    steps:
      - run: |
          echo I shouldnt be here too
          echo ${{ needs.job-three.detect.outputs.changes }}
          echo ${{ needs.job-one.outputs.changes }}

