name: Check output

on:
  push:

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: Detect changes put changes
        run: |
          echo changes=yes >> "GITHUB_OUTPUT"
          
  
  job-two:
    runs-on: ubuntu-latest
    steps:
      - name: Detect changes no changes
        run: |
          echo changes= >> "GITHUB_OUTPUT"

  job-three:
    runs-on: ubuntu-latest
    steps:
      - name: Detect changes no output
        run: |
          echo just do nothing 
    
  job-depends-one:
    name: job one must succeed
    runs-on: ubuntu-latest
    needs: [job-one]
    if: needs.job-one.outputs.changes != ''
    steps:
      - run: |
          echo I am here

  job-depends-two:
    name: job two must be skipped
    runs-on: ubuntu-latest
    needs: [job-two]
    if: needs.job-two.outputs.changes != ''
    steps:
      - run: |
          echo I Shouldn't be here

  job-depends-three:
    name: job three must succeed too
    runs-on: ubuntu-latest
    needs: [job-three]
    if: needs.job-three.outputs.changes != ''
    steps:
      - run: |
          echo I shouldn't be here too