name: Check output

on:
  push:

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: Detect changes put changes
        id: detect
        run: |
          echo changes=yes >> "$GITHUB_OUTPUT"
          
  
  job-two:
    runs-on: ubuntu-latest
    steps:
      - name: Detect changes no changes
        id: detect
        run: |
          echo changes= >> "$GITHUB_OUTPUT"

  job-three:
    runs-on: ubuntu-latest
    steps:
      - name: Detect changes no output
        id: detect
        run: |
          echo just do nothing 
    
  job-depends-one:
    name: job one must succeed
    runs-on: ubuntu-latest
    needs: [job-one]
    #if: ${{ needs.job-one.detect.outputs.changes != '' }}
    steps:
      - run: |
          echo I am here
          echo ${{ needs.job-one.detect.outputs.changes }}

  job-depends-two:
    name: job two must be skipped
    runs-on: ubuntu-latest
    needs: [job-two]
    #if: ${{ needs.job-two.detect.outputs.changes != '' }}
    steps:
      - run: |
          echo I Shouldn't be here
          echo ${{ needs.job-two.detect.outputs.changes }}


  job-depends-three:
    name: job three must be skipped too
    runs-on: ubuntu-latest
    needs: [job-three]
    #if: ${{ needs.job-three.detect.outputs.changes != '' }}
    steps:
      - run: |
          echo I shouldn't be here too
          echo ${{ needs.job-three.detect.outputs.changes }}
