name: Combiner

on:
  push:
  pull_request:

jobs:
  aaa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: green
          - color: pink
            animal: cat
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat
    steps:
      - run: echo ${{ matrix.fruit}} - ${{ matrix.animal}} - ${{ matrix.color}} - ${{ matrix.shape}}