name: Must run after partial

on:
    workflow_run: 
        workflows: 
            - Fail Partial
        types: 
            - completed 

        branches: 
            - test-this
            - test-that
            - main



jobs:
    run-depend:
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{ github.workflow }}-${{ github.ref_name }}-${{ github.head_ref }}
            - run: echo ${{ github.ref }}
            - run: echo ${{ github.event.workflow_run.conclusion }} 
            - run: echo "Dependent on fail, never run"
              if: github.event.workflow_run.conclusion == 'success'
            - run: echo "Dependent on fail always run"