name: Must run after success

on:
    workflow_run: 
        workflows: 
            - Success
        types: 
            - completed 
        branches: 
            - test-this
            - test-that
            - main



jobs:
    run-depend:
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{ github.workflow }}-${{ github.ref_name }}-${{ github.head_ref }}
            - run: echo ${{ github.ref }}
            - run: echo ${{ github.event.workflow_run.conclusion }} 
            - run: echo "Dependent on success, should run"
              if: github.event.workflow_run.conclusion == 'success'
            - run: echo "Dependent on success"