name: Detect Changes
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  detect-changes:
    name: Check if there is any changes in the binary
    runs-on: ubuntu-latest
    outputs:
      binary_changes: ${{ steps.detect-changes.outputs.binary_changes }}
    steps:
    - name: Detect changes
      id: detect-changes
      # The output need to be wrapped with double quote so that we can pipe it to $GITHUB_OUTPUT. Because of this,
      # if there is no changes, the output is double quote of empty string `""` instead of just empty string.
      run: |
         REF=$GITHUB_BASE_SHA
          if [[ -z $GITHUB_BASE_SHA ]]; then 
            echo "This is not a pull request, skipping detect changes" 
            REF="HEAD^1"
          fi
          echo "Detect changes against REF: $REF"
          OUTPUT="some changes $REF"
          echo binary_changes=\"$OUTPUT\" >> "$GITHUB_OUTPUT"
      env:
        GITHUB_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        
  tb-detect-changes:
    name: Troubleshoot
    runs-on: ubuntu-latest
    needs: [detect-changes]
    steps:
      - name: Detect changes
        run: |
          echo "I am run"
          echo "Output was \"$CHANGES\""
        env:
          CHANGES: ${{ needs.detect-changes.outputs.binary_changes }}
      