name: Hello workflow

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Docker Compose
        run: |
          docker network ls
          docker run --name my-nginx --network-alias your-nginx nginx
          docker run --rm curlimages/curl:8.8.0 -L -v my-nginx
          docker run --rm curlimages/curl:8.8.0 -L -v your-nginx