name: Checkout workflow

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checking git log
        run: |
          echo Let see what is the head show
          git log
          git show HEAD
