name: Checkout workflow

on:
  push:
  pull_request:

jobs:
  test-e2e-services:
    name: "E2E: test services"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        id: [foo, bar, buz, xxx]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: run
        run: |
          echo format ${{ format('foo-{0}-zzzzz', matrix.id)}}
          echo ${{ startsWith(format('{0}', matrix.id), buz) }}
