name: Checkout workflow

on:
  push:
  pull_request:

jobs:
  test-e2e-services:
    name: "E2E: test services"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        id: [foo, bar, buz, xxx]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: run
        if: startsWith(${{matrix.id}}, 'x')
        run: |
          echo run condition ${{ matrix.id }}
      - name: run
        run: |
          echo always run ${{ matrix.id }}