name: PR checker

on: 
  pull_request:

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps: 
        - run: echo "fine 1"

  job-two:
    runs-on: ubuntu-latest
    steps: 
        - run: echo "fine 2"

  job-three:
    runs-on: ubuntu-latest
    steps: 
        - run: echo "fine 32"
        - run: exit 1; # This will fail the job

  pr-checker:
    runs-on: ubuntu-latest
    needs: 
        - job-one
        - job-two
        - job-three
    name: PR Checker
    if: always()
    steps:
        - name: Check CI jobs result
          run: |
            # Checking whether all dependent jobs are successful
            if ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') }} ; then 
                echo "Some of the required jobs are skipped or failed";
                exit 1; 
            else
                echo "All of the required jobs are successful";
            fi