name: PR checker

on: 
  pull_request:

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps: 
        - run: echo "fine"

  job-two:
    runs-on: ubuntu-latest
    steps: 
        - run: echo "fine again"

  pr-checker:
    runs-on: ubuntu-latest
    needs: 
        - job-one
        - job-two
    name: PR Checker
    steps:
        - run: echo "pr is ok"