name: RD Listen

on: 
    repository_dispatch:
        types: 
            - ci-success

jobs:
    run-depend:
        runs-on: ubuntu-latest
        steps:
        - run: |
            echo ${{ github.event.client_payload.sha }}
            echo ${{ github.event.client_payload.ref }}
            echo '${{ toJson(github) }}'