name: RD Trigger

on: 
    push:
        branches:
        - test-this
        - test-that
        - main
        tags:
            - v*

    workflow_dispatch:

permissions:
    contents: write

    
jobs:
    run-dispatch:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: Printer
              run: |
                echo '${{ toJson(github) }}'

    run-depend:
        runs-on: ubuntu-latest
        steps:
        - name: Printer
          run: |
            echo '${{ toJson(github) }}'
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v3
          with:
            event-type: ci-success
            client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "github-event-before": "${{ github.event.before }}"}'
        - name: checkout
          uses: actions/checkout@v4
        - uses: ./.github/actions/hello-composite
          env: 
            HAHA: "custom hahahahaahah"
          
          

