name: RD Trigger

on: 
    push:
        branches:
        - test-this
        - test-that
        - main
        tags:
            - v*
jobs:
    run-depend:
        runs-on: ubuntu-latest
        steps:
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v3
          with:
            event-type: my-event
            client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
